version: '3.8'
services:

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
     - ./.env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3333
      - POSTGRES_PORT=54321
    volumes:
      - .:/app/

  db: 
    image: postgres
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3333
      - POSTGRES_PORT=54321
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: