"""renamed field in category model

Revision ID: 2bb4c344632a
Revises: 0423ee39255a
Create Date: 2022-11-24 09:56:05.923904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb4c344632a'
down_revision = '0423ee39255a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('title', sa.String(length=100), nullable=False))
    op.drop_index('ix_categories_name', table_name='categories')
    op.create_index(op.f('ix_categories_title'), 'categories', ['title'], unique=False)
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_categories_title'), table_name='categories')
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.drop_column('categories', 'title')
    # ### end Alembic commands ###
