"""fix relationship in user

Revision ID: 36da056a12c0
Revises: 14fb7aa9ccd4
Create Date: 2022-12-14 23:40:35.503586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36da056a12c0'
down_revision = '14fb7aa9ccd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articles_user_id_fkey', 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key('articles_user_id_fkey', 'articles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
