"""add_file_hash field

Revision ID: 9a7efe5d8690
Revises: fad02f828997
Create Date: 2023-01-13 18:47:14.817955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7efe5d8690'
down_revision = 'fad02f828997'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('file_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'file_hash')
    # ### end Alembic commands ###
