"""file field added

Revision ID: fad02f828997
Revises: 36da056a12c0
Create Date: 2022-12-20 23:41:59.439567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad02f828997'
down_revision = '36da056a12c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('file', sa.String(), nullable=True))
    op.alter_column('articles', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('articles', 'file')
    # ### end Alembic commands ###
